# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - '-s -w'
  goos:
    - linux
  goarch:
    - amd64
  main: ./cmd/heplify-server
  binary: '{{ .ProjectName }}'
checksum:
  name_template: 'sha256sum.txt'
  algorithm: sha256
archives:
- format: binary
  name_template: '{{ .ProjectName }}'
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    bindir: /usr/bin
    vendor: VoIPGRID
    homepage: https://www.voipgrid.nl
    maintainer: VoIPGRID <info@voipgrid.nl>
    description: |-
      Homer heplify ingester service
      HEP Capture Server & Switch in Go - with RocksDB
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/heplify-server/copyright
        file_info:
          mode: 0644
    formats:
      - deb
    deb:
      lintian_overrides:
        - changelog-file-missing-in-native-package
        - hardening-no-pie
        - no-manual-page
changelog:
  disable: true
