# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - '-s -w'
  goos:
    - linux
  goarch:
    - amd64
  main: ./cmd/heplify-server
  binary: '{{ .ProjectName }}'
checksum:
  name_template: 'sha256sum.txt'
  algorithm: sha256
archives:
- format: binary
  name_template: '{{ .ProjectName }}'
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    bindir: /usr/bin
    vendor: VoIPGRID
    homepage: https://www.voipgrid.nl
    maintainer: VoIPGRID <info@voipgrid.nl>
    description: Homer heplify ingester service
    formats:
      - deb
changelog:
  disable: true
