# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- env:
  mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - '-s -w'
  goos:
    - linux
  goarch:
    - amd64
  main: ./cmd/heplify-server
checksum:
  name_template: 'sha256sum.txt'
  algorithm: sha256
archives:
  format: binary
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
